
services:
  # üöÄ BACKEND
  backend:
    container_name: backend-riego
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      # CORRECCI√ìN AQU√ç: Usamos los mismos nombres que en el c√≥digo (DB_...)
      # Y forzamos el host a "mariadb" (el nombre del servicio de abajo)
      - DB_HOST=mariadb  
      - DB_USER=root
      - DB_PASS=admin
      - DB_NAME=riego
      - FIREBASE_ENABLED=true
      - MQTT_ENABLED=false
    depends_on:
      - mariadb
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev


  # üóÑÔ∏è MARIADB
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=riego
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # üß∞ PHPMYADMIN (opcional pero muy √∫til)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=admin
    depends_on:
      - mariadb


volumes:
  mariadb_data:

